from __future__ import annotations

from .canonical import canonical_hash, canonical_json
from .contracts_v1 import (
    MAX_ARGUMENTS,
    MAX_BEHAVIOR_USES,
    MAX_BLOCK_NESTING,
    MAX_CONSTANT_EVAL_STEPS,
    MAX_ENTITIES,
    MAX_ENUM_VARIANTS,
    MAX_EXPANDED_STATEMENT_NODES_PER_HANDLER,
    MAX_EXPRESSION_NESTING,
    MAX_FLATTENED_BEHAVIORS_PER_ENTITY,
    MAX_HANDLERS_PER_ENTITY,
    MAX_IMPORTS_PER_SOURCE,
    MAX_LINKED_CANONICAL_JSON_BYTES,
    MAX_LINKED_TOP_DECLARATIONS,
    MAX_LOCALS_PER_HANDLER,
    MAX_MATCH_ARMS,
    MAX_NESTED_STATIC_LOOPS,
    MAX_PARAMETERS,
    MAX_PURE_FUNCTION_CALL_DEPTH,
    MAX_PURE_FUNCTIONS,
    MAX_REACHABLE_MODULES,
    MAX_REACHABLE_SOURCE_BYTES,
    MAX_RECORD_FIELDS,
    MAX_RUNTIME_EVENT_CHAIN,
    MAX_RUNTIME_INSTRUCTIONS_PER_HANDLER,
    MAX_SOURCE_BYTES,
    MAX_STATES_PER_ENTITY,
    MAX_STATIC_LOOP_ITERATIONS,
    MAX_TOP_DECLARATIONS_PER_SOURCE,
    MAX_TYPE_NESTING,
    V1_LANGUAGE_VERSION,
)

DESCRIPTOR_SCHEMA_V1 = "TEV_SCRIPT_DESCRIPTOR_V3"


def v1_descriptor() -> dict[str, object]:
    descriptor: dict[str, object] = {
        "schema": DESCRIPTOR_SCHEMA_V1,
        "language_version": V1_LANGUAGE_VERSION,
        "release_status": "IMPLEMENTATION_CANDIDATE_UNCERTIFIED",
        "stable": False,
        "source_extension": ".tevs",
        "source_model": {
            "root_units": ["script", "module"],
            "exactly_one_script_root_per_link": True,
            "module_identity_from_declared_id": True,
            "filesystem_path_semantic": False,
            "network_import_resolution": False,
            "registry_import_resolution": False,
            "implicit_transitive_import_visibility": False,
        },
        "canonical_semantics": {
            "linked_program_schema": "TEV_SCRIPT_LINKED_PROGRAM_V1",
            "semantic_hash": "SHA-256 canonical JSON",
            "runtime_targets": [
                "TEV_SCRIPT_PROGRAM_IR_V2",
                "TEV_SCRIPT_PROGRAM_IR_V3",
            ],
            "automatic_target_selection": "IR_V2_IF_LOSSLESSLY_ERASABLE_ELSE_IR_V3",
        },
        "features": [
            "modules",
            "imports",
            "module_export_visibility",
            "pure_user_functions",
            "records",
            "enums",
            "Option<T>",
            "Result<T,E>",
            "exhaustive_match",
            "static_bounded_for",
            "behavior_composition",
            "typed_capabilities",
            "observation_effect_separation",
            "deterministic_local_events",
            "canonical_linked_program",
            "runtime_checkpoint_v2",
            "governed_signed_update_v2",
        ],
        "primitive_types": [
            "Bool",
            "Int",
            "Rat",
            "Text",
            "Vec2",
            "Vec3",
            "Unit",
        ],
        "boundaries": {
            "async_await": False,
            "classes_inheritance": False,
            "dynamic_code": False,
            "exceptions_as_language_control_flow": False,
            "host_native_object_references": False,
            "implicit_concurrency": False,
            "implicit_physical_effects": False,
            "reflection": False,
            "recursion": False,
            "runtime_source_compilation": False,
            "threads": False,
            "unbounded_loops": False,
            "user_defined_generics": False,
            "general_map": False,
            "general_variable_size_collection": False,
        },
        "budgets": {
            "source_bytes_per_unit": MAX_SOURCE_BYTES,
            "reachable_source_bytes": MAX_REACHABLE_SOURCE_BYTES,
            "reachable_modules": MAX_REACHABLE_MODULES,
            "imports_per_source": MAX_IMPORTS_PER_SOURCE,
            "top_declarations_per_source": MAX_TOP_DECLARATIONS_PER_SOURCE,
            "linked_top_declarations": MAX_LINKED_TOP_DECLARATIONS,
            "entities": MAX_ENTITIES,
            "states_per_flattened_entity": MAX_STATES_PER_ENTITY,
            "handlers_per_flattened_entity": MAX_HANDLERS_PER_ENTITY,
            "behavior_uses_per_component": MAX_BEHAVIOR_USES,
            "flattened_behaviors_per_entity": MAX_FLATTENED_BEHAVIORS_PER_ENTITY,
            "record_fields": MAX_RECORD_FIELDS,
            "enum_variants": MAX_ENUM_VARIANTS,
            "parameters": MAX_PARAMETERS,
            "call_arguments": MAX_ARGUMENTS,
            "lexical_block_nesting": MAX_BLOCK_NESTING,
            "expression_nesting": MAX_EXPRESSION_NESTING,
            "type_nesting": MAX_TYPE_NESTING,
            "match_arms": MAX_MATCH_ARMS,
            "static_loop_iterations": MAX_STATIC_LOOP_ITERATIONS,
            "nested_static_loops": MAX_NESTED_STATIC_LOOPS,
            "expanded_statement_nodes_per_handler": MAX_EXPANDED_STATEMENT_NODES_PER_HANDLER,
            "pure_functions": MAX_PURE_FUNCTIONS,
            "pure_function_call_depth": MAX_PURE_FUNCTION_CALL_DEPTH,
            "constant_eval_steps_per_initializer": MAX_CONSTANT_EVAL_STEPS,
            "runtime_instructions_per_handler": MAX_RUNTIME_INSTRUCTIONS_PER_HANDLER,
            "locals_per_handler": MAX_LOCALS_PER_HANDLER,
            "runtime_event_chain": MAX_RUNTIME_EVENT_CHAIN,
            "linked_canonical_json_bytes": MAX_LINKED_CANONICAL_JSON_BYTES,
        },
        "build_tooling": {
            "project_schema": "TEV_SCRIPT_PROJECT_V1",
            "project_sources_explicit": True,
            "project_globs": False,
            "project_network_resolution": False,
            "project_input_hash": True,
            "lowering_receipts": [
                "TEV_SCRIPT_LOWERING_RECEIPT_V1",
                "TEV_SCRIPT_LOWERING_RECEIPT_V2",
            ],
            "artifact_commit_policy": "EVIDENCE_SAFE_RECEIPT_LAST_V1",
        },
        "certification": {
            "v0_2_oracle_commit": "6e102f3cc3dcd131ae11e0cfc8bcfe64cccf87f5",
            "current_v1_certify_full_claim": False,
            "current_v1_language_stable_claim": False,
        },
    }
    descriptor["descriptor_hash"] = canonical_hash(descriptor)
    return descriptor


def v1_descriptor_json() -> str:
    return canonical_json(v1_descriptor())
