from __future__ import annotations

PACKAGE_VERSION = "3.1.2"
CURRENT_LANGUAGE_VERSION = "3.1.0"
CURRENT_PROFILE = "total_core"
PUBLISHED_PREDECESSOR_PACKAGE_VERSION = "3.1.1"
ARCHIVED_V31_PACKAGE_VERSION = "3.1.0"

__all__ = [
    "PACKAGE_VERSION",
    "CURRENT_LANGUAGE_VERSION",
    "CURRENT_PROFILE",
    "PUBLISHED_PREDECESSOR_PACKAGE_VERSION",
    "ARCHIVED_V31_PACKAGE_VERSION",
]
